{% set name = "lsdb" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/lsdb/archive/v{{ version }}.tar.gz
  sha256: 8f1b4bcab080139f4dc61a3d20a29d67addca79373d9747b73ba871be29ac520

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - dask
    - jinja2
    - hipscat >=0.3.5
    - numpy <2
    - pyarrow
    - deprecated
    - scipy
    - lsst-sphgeom

test:
  imports:
    - lsdb
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/lsdb
  summary: 'Large Survey Database (LSDB), an large astronomical catalog analytics tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mjuric
    - jeremykubica
    - drewoldag
    - delucchi-cmu
    - camposandro
