{% set python_min = '3.10' %}
{% set name = "lsdb" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/lsdb/archive/v{{ version }}.tar.gz
  sha256: f5860e627ebd100fa6a8c61a936f1ba1d841ffc3a7d2d3112eaf8d4ec1ce7324

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - dask
    - deprecated
    - hats >=0.4.5
    - lsst-sphgeom
    - nested-dask >=0.3.0
    - nested-pandas
    - numpy <2
    - pyarrow
    - scipy
    - jinja2

test:
  imports:
    - lsdb
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/lsdb
  summary: 'Large Survey Database (LSDB), an large astronomical catalog analytics tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - camposandro
    - delucchi-cmu
    - drewoldag
    - jeremykubica
    - mjuric
