{% set name = "lsdb" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/lsdb/archive/v{{ version }}.tar.gz
  sha256: be0fa10d9fb3b82801c798c02478ff7c1a7f516a97b6d24689f67550f3e3bc99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - dask <=2024.2.1
    - jinja2
    - hipscat >=0.2.8
    - pyarrow
    - deprecated
    - scipy
    - lsst-sphgeom

test:
  imports:
    - lsdb
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/lsdb
  summary: 'Large Survey Database (LSDB), an large astronomical catalog analytics tool'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mjuric
    - jeremykubica
    - drewoldag
    - delucchi-cmu
    - camposandro
